# Generated by Django 3.0.6 on 2020-05-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='approval',
            new_name='prediction',
        ),
    ]
